

live_rep = {"MoveJoints":"self.robot.MoveJoints",
            "movejoints":"self.robot.MoveJoints",
            "MoveLin": "self.robot.MoveLin",
            "movelin": "self.robot.MoveLin",
            "MovePose": "self.robot.MovePose",
            "movepose": "self.robot.MovePose",
            "MoveJointsRel": "self.robot.MoveJointsRel",
            "movejointsrel": "self.robot.MoveJointsRel",
            "MoveJointsVel": "self.robot.MoveJointsVel",
            "MoveLinRelTRF": "self.robot.MoveLinRelTRF",
            "MoveLinRelWRF": "self.robot.MoveLinRelWRF",
            "MoveLinVelTRF": "self.robot.MoveLinVelTRF",
            "MoveLinVelWRF": "self.robot.MoveLinVelWRF",
            "SetVelTimeout": "self.robot.SetVelTimeout",
            "SetConf": "self.robot.SetConf",
            "SetAutoConf": "self.robot.SetAutoConf",
            "SetConfTurn": "self.robot.SetConfTurn",
            "SetAutoConfTurn": "self.robot.SetAutoConfTurn",
            "SetBlending": "self.robot.SetBlending",
            "SetCartAcc": "self.robot.SetCartAcc",
            "SetCartAngVel": "self.robot.SetCartAngVel",
            "SetCartLinVel": "self.robot.SetCartLinVel",
            "GripperOpen": "self.robot.GripperOpen",
            "GripperClose": "self.robot.GripperClose",
            "MoveGripper": "self.robot.MoveGripper",
            "SetGripperForce": "self.robot.SetGripperForce",
            "SetGripperVel": "self.robot.SetGripperVel",
            "SetJointAcc": "self.robot.SetJointAcc",
            "SetJointVel": "self.robot.SetJointVel",
            "SetTRF": "self.robot.SetTRF",
            "SetWRF": "self.robot.SetWRF",
            "SetCheckpoint": "self.robot.SetCheckpoint",
            "ExpectExternalCheckpoint": "self.robot.ExpectExternalCheckpoint",
            "WaitForAnyCheckpoint": "self.robot.WaitForAnyCheckpoint",
            "WaitIdle": "self.robot.WaitIdle",
            "Delay": "self.robot.Delay",
            "StartOfflineProgram": "self.robot.StartOfflineProgram"}

moxadict = {"Input_0": "self.moxa_state[0]",
            "Input_1": "self.moxa_state[1]",
            "Input_2": "self.moxa_state[2]",
            "Input_3": "self.moxa_state[3]",
            "Input_4": "self.moxa_state[4]",
            "Input_5": "self.moxa_state[5]",
            "Input_6": "self.moxa_state[6]",
            "Input_7": "self.moxa_state[7]",
            "Output_0(True)": "self.moxa.setsingleoutput(0, True)",
            "Output_1(True)": "self.moxa.setsingleoutput(1, True)",
            "Output_2(True)": "self.moxa.setsingleoutput(2, True)",
            "Output_3(True)": "self.moxa.setsingleoutput(3, True)",
            "Output_4(True)": "self.moxa.setsingleoutput(4, True)",
            "Output_5(True)": "self.moxa.setsingleoutput(5, True)",
            "Output_6(True)": "self.moxa.setsingleoutput(6, True)",
            "Output_7(True)": "self.moxa.setsingleoutput(7, True)",
            "Output_0(False)": "self.moxa.setsingleoutput(0, False)",
            "Output_1(False)": "self.moxa.setsingleoutput(1, False)",
            "Output_2(False)": "self.moxa.setsingleoutput(2, False)",
            "Output_3(False)": "self.moxa.setsingleoutput(3, False)",
            "Output_4(False)": "self.moxa.setsingleoutput(4, False)",
            "Output_5(False)": "self.moxa.setsingleoutput(5, False)",
            "Output_6(False)": "self.moxa.setsingleoutput(6, False)",
            "Output_7(False)": "self.moxa.setsingleoutput(7, False)"}



gen_script = {"MoveJoints":"r.MoveJoints",
            "movejoints":"r.MoveJoints",
            "MoveLin": "r.MoveLin",
            "movelin": "r.MoveLin",
            "MovePose": "r.MovePose",
            "movepose": "r.MovePose",
            "MoveJointsRel": "r.MoveJointsRel",
            "movejointsrel": "r.MoveJointsRel",
            "MoveJointsVel": "r.MoveJointsVel",
            "MoveLinRelTRF": "r.MoveLinRelTRF",
            "MoveLinRelWRF": "r.MoveLinRelWRF",
            "MoveLinVelTRF": "r.MoveLinVelTRF",
            "MoveLinVelWRF": "r.MoveLinVelWRF",
            "SetVelTimeout": "r.SetVelTimeout",
            "SetConf": "r.SetConf",
            "SetAutoConf": "r.SetAutoConf",
            "SetConfTurn": "r.SetConfTurn",
            "SetAutoConfTurn": "r.SetAutoConfTurn",
            "SetBlending": "r.SetBlending",
            "SetCartAcc": "r.SetCartAcc",
            "SetCartAngVel": "r.SetCartAngVel",
            "SetCartLinVel": "r.SetCartLinVel",
            "GripperOpen": "r.GripperOpen",
            "GripperClose": "r.GripperClose",
            "MoveGripper": "r.MoveGripper",
            "SetGripperForce": "r.SetGripperForce",
            "SetGripperVel": "r.SetGripperVel",
            "SetJointAcc": "r.SetJointAcc",
            "SetJointVel": "r.SetJointVel",
            "SetTRF": "r.SetTRF",
            "SetWRF": "r.SetWRF",
            "SetCheckpoint": "r.SetCheckpoint",
            "ExpectExternalCheckpoint": "r.ExpectExternalCheckpoint",
            "WaitForAnyCheckpoint": "r.WaitForAnyCheckpoint",
            "WaitIdle": "r.WaitIdle",
            "Delay": "r.Delay",
            "StartOfflineProgram": "r.StartOfflineProgram"}
